name: employee_book
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
flutter:
  uses-material-design: true
